config:
  fenced-code-langauage: false
  fenced-code-language: false
  first-line-h1: false
  line-length: false
  link-image-reference-definitions: false
  no-duplicate-heading: false
  no-hard-tabs: false
  no-inline-html: false
  no-multiple-blanks: false
  no-trailing-spaces: false
  max-one-sentence-per-line: false
customRules:
  - "markdownlint-rule-max-one-sentence-per-line"
fix: false
globs:
  - "pages/**/*{.mdx,.md.markdown}"
