"use client";

import "./content-status.css";
import Link from "next/link";
import { usePathname } from "next/navigation";
import changed from "@/lib/changed-pages.json";

type Entry = { status: "new" | "updated" };
const MANIFEST = changed as Record<string, Entry>;

/* Review aid: if the current page's content is new or modified vs the published
   base (origin/main), show a banner so the team can spot what to review. Driven
   by lib/changed-pages.json (generated by scripts/build-changed-manifest.mjs).
   Renders nothing on unchanged pages. */
export function ContentStatus() {
  const pathname = usePathname() || "/";
  const route = pathname.replace(/\/+$/, "") || "/";
  const entry = MANIFEST[route];
  if (!entry) return null;

  const isNew = entry.status === "new";
  return (
    <div className={`content-status ${isNew ? "is-new" : "is-updated"}`} role="note">
      <span className="content-status-dot" aria-hidden="true">
        ●
      </span>
      <span className="content-status-label">{isNew ? "New page" : "Updated content"}</span>
      <span className="content-status-note">— changed on this branch, for review</span>
      <Link className="content-status-link" href="/changes">
        all changes
      </Link>
    </div>
  );
}
