import * as pagefind from "pagefind";

type FeedItem = {
  id: string,
  content_html: string,
  url: string,
  title: string,
  summary: string,
  image: string,
  date_modified: string,
  date_published: string,
  author: {
    name: string,
    url: string,
  }
}

type FeedResponse = {
  items: FeedItem[],
}

const main = async () => {
  // Pull down the contents of the feed
  const blogContents: FeedResponse = await fetch("https://authzed.com/feed/json").then(res => res.json())

  // Create a Pagefind search index to work with
  const { index } = await pagefind.createIndex({ verbose: true, logfile: "pagefind.log" });

  if (!index) {
    throw Error("could not create index")
  }

  // Index all HTML files generated by this 
  await index.addDirectory({
    // NOTE: this is relative to the current dir, so
    // when you run `pnpm gen:pagefind` you're going relative
    // to the repository root.
    path: "out",
  });

  // Add feed items to index
  await Promise.all(blogContents.items.map(item => (
    index.addCustomRecord({
      url: item.url,
      content: item.content_html,
      language: "en",
      meta: {
        title: item.title,
        image: item.image,
        summary: item.summary,
      },
      filters: {
        // TODO: add more filters?
        author: [item.author.name],
      },
      sort: {
        // TODO: make sure these work as expected
        date: item.date_modified,
        published: item.date_published,
        // This is how we rank blog stuff below docs stuff - we sort desc on this field.
        internal: "0"
      }
    })
  )))

  await index.writeFiles({
    outputPath: "public/_pagefind"
  });
}

main();
